### ISSUE TITLE
does not understand 'nijntje>1.0'

### ISSUE THREAD

**Issue by specialunderwear** [Avira/vdt.versionplugin.buildout#1]
seems that the application does not understand strict comparison.
'nijntje>=1.0' works just fine, but 'nijntje>1.0' results to syntax errors in the control file, because it generates
```

Depends: nijntje>1.0

```
instead of
```

Depends: nijntje (>1.0)
```

**Comment by specialunderwear** [comment]
Btw I will look into it and fix it. But maybe you allready know where the error lays.

**Comment by Benny-Beermann** [comment]
The error must be in https://github.com/Avira/vdt.versionplugin.buildout/blob/master/vdt/versionplugin/buildout/shared.py#L66 following
